### ISSUE TITLE
Website Feedback

### ISSUE THREAD

**Issue by joshingmachine** [yuhanx0728/yuhanx0728#1]
Hi Yuhan, sorry for the delay! Overall, this is a great site 👍 It's easy to navigate, and a great way to showcase all of the projects you've been working on. I have a few pieces of feedback I'll leave below, but it's mostly minor stuff. If anything doesn't make sense, let me know :)

<hr/>

1. You have the global navigation that sticks to the top of the screen https://github.com/yuhanx0728/yuhanx0728/blob/6f4debde498a9438094dacce22abb7963b12894b/index.html#L38-L44
It looks great on desktop, but on some mobile viewports, the navigation cuts off the beginning of the page 
<img width="382" alt="image" src="https://user-images.githubusercontent.com/2508501/53357347-b2d8a500-38fb-11e9-8980-acd76b0a6bef.png">
Some ways to fix that might include looking at [`position: sticky;`](https://developer.mozilla.org/en-US/docs/Web/CSS/position#Sticky_positioning) or using JavaScript to change when it should be fixed to the top.

<hr/>

2. It looks like there are a few places on the page that use the `<h1>` tag. 

https://github.com/yuhanx0728/yuhanx0728/blob/6f4debde498a9438094dacce22abb7963b12894b/index.html#L57
https://github.com/yuhanx0728/yuhanx0728/blob/6f4debde498a9438094dacce22abb7963b12894b/index.html#L144
https://github.com/yuhanx0728/yuhanx0728/blob/6f4debde498a9438094dacce22abb7963b12894b/index.html#L190

I would recommend only using 1 `<h1>` element on a page, as it should act kind of like the headline of the page. Usually it's the same as (or something similar to) the `<title>` that's used in the `<head>`. There are also a few places, such as 

https://github.com/yuhanx0728/yuhanx0728/blob/6f4debde498a9438094dacce22abb7963b12894b/index.html#L65

where an `<h5>` is used. Generally, you should [try to avoid skipping levels with heading elements](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Heading_Elements#Usage_notes). So in your case, I would change all of your `<h1>`s to be `<h2>`s, and change all of your `<h5>`s to be `<h3>`s.

If that changes the style of those headers to something you don't like, then you can always add a new class to those headers to style them back to how they were.

<hr/>

3. All of the `<img>`s that you use have an `alt` attribute, which is great 👍 

https://github.com/yuhanx0728/yuhanx0728/blob/6f4debde498a9438094dacce22abb7963b12894b/index.html#L64

However, with `alt` you usually want to do one of two things:
- If the image is important to the content, then use the `alt` attribute to describe it (e.g. "Labellmg detecting cars on Fifth Avenue", you could probably come up with a better description than me, though 😅).
- If the image is decorative (which I think it is in this case) setting the attribute to be `alt=""` will make it so that assistive technology recognizes it as a decorative image.

**Comment by yuhanx0728** [comment]
Hi Josh, thank you so much!! I really appreciate your comments - they will definitely help me improve my style & become more mindful about how it renders on mobile!

**Comment by yuhanx0728** [comment]
I ended up using a Boostrap template instead of making a pure HTML/CSS page from scratch for my new personal website!
